local M = {
  "lua-language-server",
  "alex",
  "bash-language-server",
  "clangd",
  "codelldb",
  "cpptools",
  "css-lsp",
  "docker-compose-language-service",
  "dockerfile-language-server",
  "emmet-language-server",
  "gitlab-ci-ls",
  "glow",
  "html-lsp",
  "js-debug-adapter",
  "json-lsp",
  "jsonlint",
  "markdownlint",
  "prettier",
  "prettierd",
  "rust-analyzer",
  "snyk",
  "stylua",
  "typescript-language-server",
  "yaml-language-server",
}
return M